//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyWebService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TraceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        private System.DateTime StartedAtField;
        
        private System.DateTime FinishedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartedAt {
            get {
                return this.StartedAtField;
            }
            set {
                if ((this.StartedAtField.Equals(value) != true)) {
                    this.StartedAtField = value;
                    this.RaisePropertyChanged("StartedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FinishedAt {
            get {
                return this.FinishedAtField;
            }
            set {
                if ((this.FinishedAtField.Equals(value) != true)) {
                    this.FinishedAtField = value;
                    this.RaisePropertyChanged("FinishedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadField, value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraceDestination", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TraceDestination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.MyWebService1.ArrayOfString ExpectedMachineNamesField;
        
        private int ExpectedElapsedMilisecondsMaxField;
        
        private int ExpectedElapsedMilisecondsAverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadRegexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExpectedIdentity {
            get {
                return this.ExpectedIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedIdentityField, value) != true)) {
                    this.ExpectedIdentityField = value;
                    this.RaisePropertyChanged("ExpectedIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebApplication1.MyWebService1.ArrayOfString ExpectedMachineNames {
            get {
                return this.ExpectedMachineNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedMachineNamesField, value) != true)) {
                    this.ExpectedMachineNamesField = value;
                    this.RaisePropertyChanged("ExpectedMachineNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ExpectedElapsedMilisecondsMax {
            get {
                return this.ExpectedElapsedMilisecondsMaxField;
            }
            set {
                if ((this.ExpectedElapsedMilisecondsMaxField.Equals(value) != true)) {
                    this.ExpectedElapsedMilisecondsMaxField = value;
                    this.RaisePropertyChanged("ExpectedElapsedMilisecondsMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ExpectedElapsedMilisecondsAverage {
            get {
                return this.ExpectedElapsedMilisecondsAverageField;
            }
            set {
                if ((this.ExpectedElapsedMilisecondsAverageField.Equals(value) != true)) {
                    this.ExpectedElapsedMilisecondsAverageField = value;
                    this.RaisePropertyChanged("ExpectedElapsedMilisecondsAverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PayloadDescription {
            get {
                return this.PayloadDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadDescriptionField, value) != true)) {
                    this.PayloadDescriptionField = value;
                    this.RaisePropertyChanged("PayloadDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PayloadRegex {
            get {
                return this.PayloadRegexField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadRegexField, value) != true)) {
                    this.PayloadRegexField = value;
                    this.RaisePropertyChanged("PayloadRegex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebService1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name PingResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        WebApplication1.MyWebService1.PingResponse Ping(WebApplication1.MyWebService1.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.PingResponse> PingAsync(WebApplication1.MyWebService1.PingRequest request);
        
        // CODEGEN: Generating message contract since element name destination from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Trace", ReplyAction="*")]
        WebApplication1.MyWebService1.TraceResponse Trace(WebApplication1.MyWebService1.TraceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Trace", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.TraceResponse> TraceAsync(WebApplication1.MyWebService1.TraceRequest request);
        
        // CODEGEN: Generating message contract since element name TracesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Traces", ReplyAction="*")]
        WebApplication1.MyWebService1.TracesResponse Traces(WebApplication1.MyWebService1.TracesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Traces", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.TracesResponse> TracesAsync(WebApplication1.MyWebService1.TracesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(WebApplication1.MyWebService1.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(WebApplication1.MyWebService1.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Trace", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.TraceRequestBody Body;
        
        public TraceRequest() {
        }
        
        public TraceRequest(WebApplication1.MyWebService1.TraceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string destination;
        
        public TraceRequestBody() {
        }
        
        public TraceRequestBody(string destination) {
            this.destination = destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.TraceResponseBody Body;
        
        public TraceResponse() {
        }
        
        public TraceResponse(WebApplication1.MyWebService1.TraceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.MyWebService1.TraceResult[] TraceResult;
        
        public TraceResponseBody() {
        }
        
        public TraceResponseBody(WebApplication1.MyWebService1.TraceResult[] TraceResult) {
            this.TraceResult = TraceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TracesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Traces", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.TracesRequestBody Body;
        
        public TracesRequest() {
        }
        
        public TracesRequest(WebApplication1.MyWebService1.TracesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TracesRequestBody {
        
        public TracesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TracesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TracesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.MyWebService1.TracesResponseBody Body;
        
        public TracesResponse() {
        }
        
        public TracesResponse(WebApplication1.MyWebService1.TracesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TracesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.MyWebService1.TraceDestination[] TracesResult;
        
        public TracesResponseBody() {
        }
        
        public TracesResponseBody(WebApplication1.MyWebService1.TraceDestination[] TracesResult) {
            this.TracesResult = TracesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.MyWebService1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.MyWebService1.WebService1Soap>, WebApplication1.MyWebService1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.MyWebService1.PingResponse WebApplication1.MyWebService1.WebService1Soap.Ping(WebApplication1.MyWebService1.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            WebApplication1.MyWebService1.PingRequest inValue = new WebApplication1.MyWebService1.PingRequest();
            inValue.Body = new WebApplication1.MyWebService1.PingRequestBody();
            WebApplication1.MyWebService1.PingResponse retVal = ((WebApplication1.MyWebService1.WebService1Soap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.PingResponse> WebApplication1.MyWebService1.WebService1Soap.PingAsync(WebApplication1.MyWebService1.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.MyWebService1.PingResponse> PingAsync() {
            WebApplication1.MyWebService1.PingRequest inValue = new WebApplication1.MyWebService1.PingRequest();
            inValue.Body = new WebApplication1.MyWebService1.PingRequestBody();
            return ((WebApplication1.MyWebService1.WebService1Soap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.MyWebService1.TraceResponse WebApplication1.MyWebService1.WebService1Soap.Trace(WebApplication1.MyWebService1.TraceRequest request) {
            return base.Channel.Trace(request);
        }
        
        public WebApplication1.MyWebService1.TraceResult[] Trace(string destination) {
            WebApplication1.MyWebService1.TraceRequest inValue = new WebApplication1.MyWebService1.TraceRequest();
            inValue.Body = new WebApplication1.MyWebService1.TraceRequestBody();
            inValue.Body.destination = destination;
            WebApplication1.MyWebService1.TraceResponse retVal = ((WebApplication1.MyWebService1.WebService1Soap)(this)).Trace(inValue);
            return retVal.Body.TraceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.TraceResponse> WebApplication1.MyWebService1.WebService1Soap.TraceAsync(WebApplication1.MyWebService1.TraceRequest request) {
            return base.Channel.TraceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.MyWebService1.TraceResponse> TraceAsync(string destination) {
            WebApplication1.MyWebService1.TraceRequest inValue = new WebApplication1.MyWebService1.TraceRequest();
            inValue.Body = new WebApplication1.MyWebService1.TraceRequestBody();
            inValue.Body.destination = destination;
            return ((WebApplication1.MyWebService1.WebService1Soap)(this)).TraceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.MyWebService1.TracesResponse WebApplication1.MyWebService1.WebService1Soap.Traces(WebApplication1.MyWebService1.TracesRequest request) {
            return base.Channel.Traces(request);
        }
        
        public WebApplication1.MyWebService1.TraceDestination[] Traces() {
            WebApplication1.MyWebService1.TracesRequest inValue = new WebApplication1.MyWebService1.TracesRequest();
            inValue.Body = new WebApplication1.MyWebService1.TracesRequestBody();
            WebApplication1.MyWebService1.TracesResponse retVal = ((WebApplication1.MyWebService1.WebService1Soap)(this)).Traces(inValue);
            return retVal.Body.TracesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.MyWebService1.TracesResponse> WebApplication1.MyWebService1.WebService1Soap.TracesAsync(WebApplication1.MyWebService1.TracesRequest request) {
            return base.Channel.TracesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.MyWebService1.TracesResponse> TracesAsync() {
            WebApplication1.MyWebService1.TracesRequest inValue = new WebApplication1.MyWebService1.TracesRequest();
            inValue.Body = new WebApplication1.MyWebService1.TracesRequestBody();
            return ((WebApplication1.MyWebService1.WebService1Soap)(this)).TracesAsync(inValue);
        }
    }
}
